### ISSUE TITLE
getCourse: name 값에 과목명만 넣도록 수정

### ISSUE THREAD

**Issue by Kangdyu** [Kangdyu/i-ppendix#16]
현재 `getCourse` 를 통해 리턴되는 데이터 중 `name`의 경우, `모바일앱프로그래밍실습_SWE3047_42(김영훈)` 처럼 뒤에 과목 코드 및 교수님 성함까지 같이 붙어 나옴.
`모바일앱프로그래밍실습` 만 넣도록 수정

담당자: @chadh0829

**Comment by chadh0829** [comment]
바로 수정하겠습니다
